Verbose Inventory Quantities
open-osrs/runelite pull request #2814
Opened 2020-09-22 14:29 UTC by ImNoOSRS

A toggle which makes it possible to show full lenght inventory quantities.

2020-09-22 14:29 UTC, Smeety commented
;D

2020-09-22 17:43 UTC, Lucwousin requested changes
You should also change the commit message, `-` isn't really descriptive. Other than that, looks good! Make sure to also create a plugin which utilizes this functionality :P

2020-09-22 17:43 UTC, Lucwousin commented on runelite-api/src/main/java/net/runelite/api/Client.java
> +	void setVerbose(boolean state);
Change this method name to actually describe what's made verbose (ie setItemQuantitiesVerbose)

2020-09-22 17:43 UTC, Lucwousin commented on runelite-mixins/src/main/java/net/runelite/mixins/VerboseInventoryMixin.java
> +package net.runelite.mixins;
This is missing a copyright header

2020-09-22 17:43 UTC, Lucwousin commented on runelite-mixins/src/main/java/net/runelite/mixins/VerboseInventoryMixin.java
> +public abstract class VerboseInventoryMixin implements RSClient
VerboseInventoryQuantitiesMixin? It only makes the quantities more verbose, not the inventory in it's entirety

2020-09-22 17:43 UTC, Lucwousin commented on runelite-mixins/src/main/java/net/runelite/mixins/VerboseInventoryMixin.java
> +    public void setVerbose(boolean state)
Add `@Override` to this, so you can tell it's implementation for the interface more easily

2020-09-22 17:43 UTC, Lucwousin commented on runelite-mixins/src/main/java/net/runelite/mixins/VerboseInventoryMixin.java
> +        long decimal = n;
Remove this unused variable

2020-09-22 17:53 UTC, Lucwousin commented on runescape-client/src/main/java/class194.java
> +	@Export("inventoryQuantityFormat")
there's no import for Export

2020-09-22 18:26 UTC, ImNoOSRS commented
Thanks for the edits @Lucwousin i really do pull requests so its quite new to me i tried renaming the commit from - to something else but i didnt really figure out how to do that

2020-09-24 11:40 UTC, Lucwousin approved these changes

2020-09-24 11:41 UTC, merged