Added Animation runelite api file. Also renamed "skin" to "skeleton".
open-osrs/runelite pull request #2867
Opened 2020-11-22 19:48 UTC by somawheels

2020-11-22 22:00 UTC, swazrgb requested changes

2020-11-28 14:30 UTC, ThatGamerBlue requested changes

2020-11-28 14:30 UTC, ThatGamerBlue commented on runelite-api/src/main/java/net/runelite/api/Animation.java
> +package net.runelite.api;
license header

2020-11-28 14:30 UTC, ThatGamerBlue commented on runelite-api/src/main/java/net/runelite/api/DualNode.java
> +package net.runelite.api;
license header

2020-11-28 14:30 UTC, ThatGamerBlue commented on runelite-api/src/main/java/net/runelite/api/DualNode.java
> +	void unlinkDual();
this method is unimplemented, need to `@Import` it in rs-api

2020-11-28 14:30 UTC, ThatGamerBlue commented on runelite-api/src/main/java/net/runelite/api/Frames.java
> +package net.runelite.api;
license header

2020-11-28 14:30 UTC, ThatGamerBlue commented on runelite-api/src/main/java/net/runelite/api/Skeleton.java
> +package net.runelite.api;
license header

2020-12-03 19:06 UTC, ThatGamerBlue approved these changes

2020-12-03 22:16 UTC, merged