Refactored/exported some fields and methods
open-osrs/runelite pull request #2974
Opened 2021-03-21 17:49 UTC by Jonatino

Renamed some fields/methods regarding cache logic in the runescape-client project.

2021-03-23 18:12 UTC, Jonatino commented
Need to remove static field imports inside RS interfaces.

2021-03-26 12:00 UTC, Lucwousin requested changes

2021-03-26 12:00 UTC, Lucwousin commented on runescape-client/src/main/java/Login.java
> +}
Revert this file

2021-03-26 12:00 UTC, Lucwousin commented on runescape-client/src/main/java/WorldMapRectangle.java
> +}
Revert this file

2021-03-26 12:00 UTC, Lucwousin commented on runescape-client/src/main/java/class170.java
> +}
Revert this file

2021-03-26 12:00 UTC, Lucwousin commented on runescape-client/src/main/java/class13.java
> +}
Revert this file

2021-03-26 12:00 UTC, Lucwousin commented on runescape-client/src/main/java/class171.java
> +{
This bracket is supposed to go next to the class declaration but it doesn't really matter thát much

2021-03-26 12:00 UTC, Lucwousin commented on runescape-client/src/main/java/class224.java
> +	@Export("redrawMiniMapIcons")
I think this does more than just draw icons - if I'm correct, it draws the entire minimap :P

Maybe `createMinimapSprite`?

2021-03-26 16:33 UTC, merged